# Generated by Django 4.0.2 on 2022-04-04 12:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_delete_employee_books_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(default=datetime.timedelta(days=5))),
                ('status', models.CharField(choices=[('orderplaced', 'orderplaced'), ('dispatched', 'dispatched'), ('in_transit', 'in_transit'), ('deliverd', 'deliverd'), ('order_cancelled', 'order_cancelled')], default='orderplaced', max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
